name: Add Gradle Wrapper

on:
  workflow_dispatch:
    inputs:
      gradle_version:
        description: "Gradle version to generate wrapper for"
        required: true
        default: "8.9"

permissions:
  contents: write

jobs:
  add-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Download Gradle ${{ inputs.gradle_version }}
        run: |
          curl -sSL -o gradle.zip "https://services.gradle.org/distributions/gradle-${{ inputs.gradle_version }}-bin.zip"
          unzip -q gradle.zip

      - name: Generate Gradle Wrapper in android/
        run: |
          ./gradle-${{ inputs.gradle_version }}/bin/gradle -p android wrapper --gradle-version ${{ inputs.gradle_version }}
          chmod +x android/gradlew

      - name: Commit wrapper files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add android/gradlew android/gradlew.bat android/gradle/wrapper/gradle-wrapper.jar android/gradle/wrapper/gradle-wrapper.properties
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(android): add Gradle Wrapper (${{ inputs.gradle_version }})"
            git push origin HEAD:${GITHUB_REF_NAME:-main}
          fi
